#! /usr/bin/env python

import doctest
import os.path

def test(filename, verbose=False):
    base, ext = os.path.splitext(filename)
    name = base.replace(os.path.sep, '.')
    mod = __import__(name, None, None, ['x'])
    doctest.testmod(mod, verbose=verbose)

if __name__ == "__main__":
    import sys
    sys.path.insert(0, '.')

    if '-v' in sys.argv:
        sys.argv.remove('-v')
        verbose = True
    else:
        verbose = False

    test(sys.argv[1], verbose)
