#! /usr/bin/env python
"""Script to open source file of a python module in vim.

In the middle of serious python hacking, you might like to see how a class or function is implemented.
This utility helps you by opening the module of interest in vim. 

Usage:
    $ pyvi os.path
"""

from __future__ import print_function

import sys
import os

from importlib.util import find_spec

def open_module(module_name):
    module_spec = find_spec(module_name)
    module_source = module_spec.origin

    # print(module_source)

    if module_source.endswith('.pyc'):
        module_source = module_source[:-1]

    os.chdir(os.path.dirname(module_source))
    os.execlp('view', 'view', '-M', module_source)

if __name__ == '__main__':
    open_module(sys.argv[1])
