#! /usr/bin/env python
"""
repr: prints each line as python repr.
"""
from __future__ import print_function

import fileinput


def main():
    for line in fileinput.input():
        print(repr(line)[1:-1]) # strip the quotes

if __name__ == "__main__":
    main()
